spring:
  profiles: default
character:
  firstname: "DefaultName"
  lastname: "DefaultLastName"

---

spring:
  profiles: ci
character:
  firstname: "Tyrande"
  lastname: "Wisperwind"

---

spring:
  profiles: qa
character:
  firstname: "Illidan"
  lastname: "Stormrage"
